name: Lint Commit Messages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to read the history of commits

      - name: Setup Node.js (Required for Commitlint)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Commitlint
        run: npm install @commitlint/config-conventional

      - name: Validate current commit (Push)
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits (Pull Request)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose